name: "Default Setup"
description: "Demonstrates a possible terminal configuration option"
window:
  tabs:
    - profile: "PowerShell"
      directory: "%USERPROFILE%"
      title: "Development"
      splits:
        - direction: "vertical"
          size: 0.5

        - direction: "horizontal"
          directory: "%USERPROFILE%"
          size: 0.3


    - profile: "PowerShell"
      directory: "%USERPROFILE%"
      title: "Tab 2"

